version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@6.7.0
  aws-ecs: circleci/aws-ecs@1.1.0
workflows:
  build_and_push_image:
    jobs:
      - aws-ecr/build-and-push-image:
          name: Nginx Deploy
          account-url: AWS_ECR_ACCOUNT_URL
          region: AWS_REGION
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          create-repo: true
          path: ./docker/nginx
          repo: nginx
          tag: latest
          dockerfile: DockerfilePRO
          filters:
            branches:
              only: master
      - aws-ecr/build-and-push-image:
          name: Rails Deploy
          account-url: AWS_ECR_ACCOUNT_URL
          region: AWS_REGION
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          create-repo: true
          path: ./docker/rails
          repo: rails
          tag: latest
          dockerfile: DockerfilePRO
          filters:
            branches:
              only: master
      - aws-ecs/deploy-service-update:
          requires:
            - aws-ecr/build-and-push-image
          family: '${TASK_DEFINITION_NAME}-service'
          cluster-name: '${ECS_ARN}'
#AWS_ECR_ACCOUNT_URL => ${アカウントID}.dkr.ecr.${リージョン}.amazonaws.com